# Istio Base Values
# Base configuration for Istio service mesh

meshConfig:
  accessLogFile: "/dev/stdout"
  enableTracing: true
  defaultConfig:
    tracing:
      zipkin:
        address: zipkin.istio-system:9411
    proxyMetadata:
      # Enable Envoy's access logging, required for proper telemetry
      ISTIO_META_PROXY_XDS_VIA_AGENT: "true"

pilot:
  enabled: true
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 3
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi
    limits:
      cpu: 1000m
      memory: 4096Mi
  
  # Configuration for tracing
  traceSampling: 1.0

# Enable Istio CNI plugin
cni:
  enabled: true

# Global TLS settings
global:
  # For better security, enable mTLS by default
  mtls:
    enabled: true

  # Default proxy settings
  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    
    # Secure defaults for healthCheck
    holdApplicationUntilProxyStarts: true
    accessLogFile: "/dev/stdout"
    accessLogFormat: ""
    accessLogEncoding: "TEXT"
    componentLogLevel: "misc:error"
    logLevel: info

  # Default config for proxy sidecar injection
  defaultPodDisruptionBudget:
    enabled: true

# Istio gateway configuration
gateways:
  istio-ingressgateway:
    enabled: true
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 3
    serviceAnnotations:
      cloud.google.com/app-protocols: '{"https":"HTTPS","http2":"HTTP2"}'
    ports:
    - port: 15021
      targetPort: 15021
      name: status-port
    - port: 80
      targetPort: 8080
      name: http2
    - port: 443
      targetPort: 8443
      name: https
    type: LoadBalancer
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi

  istio-egressgateway:
    enabled: true
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 3
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi

# Prometheus integration
prometheus:
  enabled: true
  hub: docker.io/prom
  tag: v2.41.0

# Kiali integration for visualization
kiali:
  enabled: true
  dashboard:
    grafanaURL: http://grafana.monitoring:3000
    jaegerURL: http://jaeger-query.istio-system:16686

# Jaeger for distributed tracing
tracing:
  enabled: true
  provider: jaeger
  jaeger:
    hub: docker.io/jaegertracing
    tag: 1.41.0