controller:
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  
  # Set compute resources
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
    limits:
      cpu: 800m
      memory: 512Mi
  
  # Use Google's LoadBalancer
  service:
    annotations:
      cloud.google.com/load-balancer-type: "External"
    externalTrafficPolicy: Local
  
  # Enable Prometheus metrics
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  
  # Basic configuration
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "false"
    # Optimizations for production
    keep-alive: "75"
    keep-alive-requests: "100"
    proxy-body-size: "20m"
    proxy-buffer-size: "4k"
    proxy-connect-timeout: "15"
    proxy-read-timeout: "60"
    proxy-send-timeout: "60"
    
  # Health check paths
  healthCheckPath: "/healthz"
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    
# Default backend for 404 pages
defaultBackend:
  enabled: true
  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 5m
      memory: 10Mi