# Default values for hello-world
replicaCount: 2

image:
  repository: gcr.io/your-gcp-project-id/hello-world
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: hello-world.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: hello-world-tls
    hosts:
    - hello-world.example.com

nodeSelector: {}

tolerations: []

affinity: {}

environment: dev

# Add-on specific configurations
useExternalSecrets: true  # Set to true to use External Secrets Operator
mountTLSCert: false       # Set to true to mount TLS certificates in the pod
