# Default values for hello-world
replicaCount: 2

image:
  repository: gcr.io/your-gcp-project-id/hello-world
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: "gce"
  hosts:
    - host: hello-world.example.com
      paths:
        - path: /
          pathType: Prefix

nodeSelector: {}

tolerations: []

affinity: {}

environment: dev
