name: Provision Dev GKE Cluster

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email for Let''s Encrypt certificate'
        required: false
        default: 'admin@example.com'
  workflow_run:
    workflows: ["Crossplane Bootstrap"]
    types:
      - completed

jobs:
  provision-cluster:
    name: Provision Dev GKE Cluster with Crossplane
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.0'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Download Kubeconfig from Terraform Workflow
        uses: actions/download-artifact@v3
        with:
          name: dev-kubeconfig
          path: ./tmp

      - name: Set KUBECONFIG Environment Variable
        run: |
          echo "KUBECONFIG=$(pwd)/tmp/kubeconfig.yaml" >> $GITHUB_ENV
          chmod 600 $(pwd)/tmp/kubeconfig.yaml

      - name: Prepare and Apply Dev Cluster Claim
        run: |
          # Replace placeholders in dev cluster claim
          sed -i "s/\${GCP_PROJECT_ID}/${{ secrets.GCP_PROJECT_ID }}/g" crossplane/xresources/dev-gke-cluster-claim.yaml
          
          # Apply dev GKE cluster claim
          kubectl apply -f crossplane/xresources/dev-gke-cluster-claim.yaml
          
          # Wait for dev cluster to be ready (this may take some time)
          echo "Waiting for dev GKE cluster to be provisioned (may take 10+ minutes)..."
          kubectl wait --for=condition=ready gkecluster.platform.commercelab.io/dev-gke-cluster --timeout=900s
          
          # Get dev cluster name
          DEV_CLUSTER_NAME=$(kubectl get gkecluster.platform.commercelab.io/dev-gke-cluster -o jsonpath='{.status.clusterName}')
          echo "Dev cluster name: $DEV_CLUSTER_NAME"
          
          # Get dev cluster credentials
          gcloud container clusters get-credentials $DEV_CLUSTER_NAME --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}
          
          # Save dev cluster kubeconfig for future use
          KUBECONFIG_DEV="$(pwd)/dev-cluster-kubeconfig.yaml"
          gcloud container clusters get-credentials $DEV_CLUSTER_NAME --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }} --kubeconfig $KUBECONFIG_DEV
          
          # Store dev cluster kubeconfig
          echo "DEV_KUBECONFIG_DATA=$(cat $KUBECONFIG_DEV | base64 -w 0)" >> $GITHUB_ENV

      - name: Store Dev Cluster Kubeconfig
        id: store-dev-kubeconfig
        uses: actions/upload-artifact@v3
        with:
          name: dev-cluster-kubeconfig
          path: dev-cluster-kubeconfig.yaml
          retention-days: 1
          
      - name: Install Add-ons on Dev Cluster
        run: |
          # Set up environment variables
          DEV_CLUSTER_NAME=$(kubectl get gkecluster.platform.commercelab.io/dev-gke-cluster -o jsonpath='{.status.clusterName}')
          EMAIL="${{ github.event.inputs.email || 'admin@example.com' }}"
          GCP_PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
          GCP_EXTERNAL_SECRETS_SA="dev-external-secrets-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          
          echo "Installing add-ons on cluster $DEV_CLUSTER_NAME..."
          
          # Set context to dev cluster
          KUBECONFIG_DEV="$(pwd)/dev-cluster-kubeconfig.yaml"
          export KUBECONFIG=$KUBECONFIG_DEV
          
          # Run the comprehensive add-ons installation script
          ./kubernetes-addons/install.sh "$EMAIL" "$GCP_PROJECT_ID" "$GCP_EXTERNAL_SECRETS_SA"
          
          # Verify add-ons installation
          echo "Verifying add-ons installation..."
          kubectl get pods -n ingress-nginx
          kubectl get pods -n cert-manager
          kubectl get pods -n reloader
          kubectl get pods -n external-secrets
          kubectl get clusterissuer letsencrypt-staging
          
          echo "Add-ons installation complete!"