name: Terraform Infrastructure Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Terraform Init
        working-directory: infra/environments/${{ github.event.inputs.environment }}
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.GCP_TERRAFORM_STATE_BUCKET }}" \
            -backend-config="prefix=${{ github.event.inputs.environment }}"

      - name: Terraform Plan
        working-directory: infra/environments/${{ github.event.inputs.environment }}
        run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

      - name: Terraform Apply
        working-directory: infra/environments/${{ github.event.inputs.environment }}
        run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

      - name: Save Terraform Outputs
        working-directory: infra/environments/${{ github.event.inputs.environment }}
        run: |
          terraform output -json > terraform-outputs.json
          # Extract kubeconfig and store it for subsequent workflows
          cat terraform-outputs.json | jq -r '.kubeconfig.value' > kubeconfig.yaml
          echo "KUBECONFIG_DATA=$(cat kubeconfig.yaml | base64 -w 0)" >> $GITHUB_ENV

      - name: Store Kubeconfig
        id: store-kubeconfig
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}-kubeconfig
          path: infra/environments/${{ github.event.inputs.environment }}/kubeconfig.yaml
          retention-days: 1