apiVersion: platform.commercelab.io/v1alpha1
kind: GKECluster
metadata:
  name: dev-gke-cluster
  labels:
    environment: dev
    name: devcluster
    role: application
spec:
  providerConfigRef:
    name: default
  clusterName: dev-gke-cluster
  projectID: ${GCP_PROJECT_ID}
  location: us-central1
  clusterVersion: 1.28
  releaseChannel: REGULAR
  maintenanceWindow:
    startTime: "03:00"
    recurrence: "FREQ=WEEKLY;BYDAY=SA,SU"
  
  # Network configuration - Use environment-specific VPC (connected to shared VPC via peering)
  networkConfig:
    networkName: dev-vpc
    subnetName: dev-subnet
    podCidrBlock: "10.32.0.0/16"  # Environment-specific pod CIDR
    serviceCidrBlock: "10.33.0.0/20"  # Environment-specific service CIDR
    # VPC peering to the shared VPC is already configured via Terraform
  
  # Node configuration
  nodeConfig:
    nodeCount: 1
    machineType: e2-standard-2
    diskSizeGb: 50
    diskType: pd-standard
    serviceAccount: shared-gke-node-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com
    autoscaling:
      minNodeCount: 1
      maxNodeCount: 3
    labels:
      environment: dev
      role: application
    
  # Security configuration  
  securityConfig:
    enableShieldedNodes: true
    enableIntegrityMonitoring: true
    enableSecureBoot: true
    enableNetworkPolicy: true
    privateClusterConfig:
      enablePrivateNodes: true
      enablePrivateEndpoint: false
      masterIpv4CidrBlock: "172.16.1.16/28" # Specific to dev environment
      masterAuthorizedNetworks:
        - cidrBlock: "10.0.0.0/20" # Shared VPC subnet CIDR to allow communication from infracluster