apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgkeclusters.platform.commercelab.io
spec:
  group: platform.commercelab.io
  names:
    kind: XGKECluster
    plural: xgkeclusters
  claimNames:
    kind: GKECluster
    plural: gkeclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Basic Cluster Configuration
                providerConfigRef:
                  description: Reference to the provider configuration
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
                clusterName:
                  description: Name for the GKE cluster
                  type: string
                projectID:
                  description: GCP Project ID where the cluster will be created
                  type: string
                location:
                  description: GCP region for the cluster
                  type: string
                  default: us-central1
                clusterVersion:
                  description: Kubernetes version for the cluster
                  type: string
                  default: latest
                releaseChannel:
                  description: Release channel for GKE
                  type: string
                  default: REGULAR
                  enum:
                    - RAPID
                    - REGULAR
                    - STABLE
                
                # Maintenance Configuration
                maintenanceWindow:
                  description: Maintenance window configuration
                  type: object
                  properties:
                    startTime:
                      description: Start time for maintenance window in HH:MM format
                      type: string
                      default: "03:00"
                    endTime:
                      description: End time for maintenance window in HH:MM format (for recurring windows)
                      type: string
                    recurrence:
                      description: RFC 5545 RRULE for when maintenance windows occur
                      type: string
                  required:
                    - startTime
                
                # Network Configuration
                networkConfig:
                  description: Configuration for the cluster's network in the shared VPC
                  type: object
                  properties:
                    networkName:
                      description: Name of the shared VPC network
                      type: string
                      default: "shared-vpc"
                    hostProjectID:
                      description: The project ID of the shared VPC host project
                      type: string
                    subnetName:
                      description: Name of the environment subnet in the shared VPC
                      type: string
                    podRangeName:
                      description: Secondary range name for pods in the shared VPC
                      type: string
                    serviceRangeName:
                      description: Secondary range name for services in the shared VPC
                      type: string
                  required:
                    - subnetName
                    - hostProjectID
                
                # Node Configuration
                nodeConfig:
                  description: Node pool configuration
                  type: object
                  properties:
                    nodeCount:
                      description: Number of nodes in the node pool
                      type: integer
                      default: 1
                    machineType:
                      description: GCP machine type
                      type: string
                      default: e2-standard-2
                    diskSizeGb:
                      description: Size of the disk in GB
                      type: integer
                      default: 100
                    diskType:
                      description: Type of disk
                      type: string
                      default: pd-standard
                    serviceAccount:
                      description: Service account email to use for nodes
                      type: string
                    autoscaling:
                      description: Node autoscaling configuration
                      type: object
                      properties:
                        minNodeCount:
                          description: Minimum number of nodes
                          type: integer
                          default: 1
                        maxNodeCount:
                          description: Maximum number of nodes
                          type: integer
                          default: 5
                      required:
                        - minNodeCount
                        - maxNodeCount
                    labels:
                      description: Labels to apply to the nodes
                      type: object
                      additionalProperties:
                        type: string
                  required:
                    - serviceAccount
                
                # Security Configuration
                securityConfig:
                  description: Security configuration for the cluster
                  type: object
                  properties:
                    enableShieldedNodes:
                      description: Enable Shielded Nodes
                      type: boolean
                      default: true
                    enableIntegrityMonitoring:
                      description: Enable integrity monitoring for Shielded Nodes
                      type: boolean
                      default: true
                    enableSecureBoot:
                      description: Enable Secure Boot for Shielded Nodes
                      type: boolean
                      default: true
                    enableNetworkPolicy:
                      description: Enable Kubernetes Network Policy
                      type: boolean
                      default: true
                    enableBinaryAuthorization:
                      description: Enable Binary Authorization
                      type: boolean
                      default: false
                    privateClusterConfig:
                      description: Private cluster configuration
                      type: object
                      properties:
                        enablePrivateNodes:
                          description: Enable private nodes
                          type: boolean
                          default: true
                        enablePrivateEndpoint:
                          description: Enable private endpoint
                          type: boolean
                          default: false
                        masterIpv4CidrBlock:
                          description: CIDR block for the master's private endpoint
                          type: string
                        masterAuthorizedNetworks:
                          description: CIDRs that can access the master endpoint
                          type: array
                          items:
                            type: object
                            properties:
                              cidrBlock:
                                description: CIDR block
                                type: string
                              displayName:
                                description: Display name for the CIDR block
                                type: string
                                default: "Authorized Network"
                          default:
                            - cidrBlock: "10.0.0.0/8"
                              displayName: "Private Network"
                
                # High Availability Configuration
                highAvailabilityConfig:
                  description: High availability configuration
                  type: object
                  properties:
                    regionalCluster:
                      description: Whether to create a regional cluster
                      type: boolean
                      default: true
                    maintenanceExclusionWindows:
                      description: Maintenance exclusion windows (e.g., for holiday blackout periods)
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            description: Name of the exclusion window
                            type: string
                          startTime:
                            description: Start time in RFC3339 format
                            type: string
                          endTime:
                            description: End time in RFC3339 format
                            type: string
                          description:
                            description: Description of why this exclusion window exists
                            type: string
              required:
                - providerConfigRef
                - projectID
                - networkConfig
                - nodeConfig
            status:
              type: object
              properties:
                clusterName:
                  description: The name of the created cluster
                  type: string
                endpoint:
                  description: The endpoint of the cluster
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string