apiVersion: platform.commercelab.io/v1alpha1
kind: GKECluster
metadata:
  name: prod-gke-cluster
  labels:
    environment: prod
    name: prodcluster
    role: application
spec:
  providerConfigRef:
    name: default
  clusterName: prod-gke-cluster
  projectID: ${GCP_PROJECT_ID}
  location: us-central1
  clusterVersion: 1.28
  releaseChannel: STABLE
  maintenanceWindow:
    startTime: "01:00"
    recurrence: "FREQ=WEEKLY;BYDAY=SA"
  
  # Network configuration - Dedicated VPC architecture
  networkConfig:
    useExistingNetwork: false
    # No host project needed for dedicated VPC architecture
  
  # Node configuration
  nodeConfig:
    nodeCount: 3
    machineType: e2-standard-4
    diskSizeGb: 100
    diskType: pd-ssd
    serviceAccount: gke-node-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com
    autoscaling:
      minNodeCount: 3
      maxNodeCount: 7
    labels:
      environment: prod
      role: application
    
  # Security configuration  
  securityConfig:
    enableShieldedNodes: true
    enableIntegrityMonitoring: true
    enableSecureBoot: true
    enableNetworkPolicy: true
    enableBinaryAuthorization: true
    privateClusterConfig:
      enablePrivateNodes: true
      enablePrivateEndpoint: false
      masterIpv4CidrBlock: "172.16.3.16/28" # Specific to production environment
      masterAuthorizedNetworks:
        - cidrBlock: "0.0.0.0/0" # Allow access from the infrastructure cluster
        
  # High availability configuration
  highAvailabilityConfig:
    regionalCluster: true
    maintenanceExclusionWindows:
      - name: "black-friday"
        startTime: "2024-11-20T00:00:00Z"
        endTime: "2024-12-01T00:00:00Z"
        description: "Black Friday/Cyber Monday exclusion window"