apiVersion: platform.commercelab.io/v1alpha1
kind: GKECluster
metadata:
  name: prod-gke-cluster
  labels:
    environment: prod
    name: prodcluster
    role: application
spec:
  providerConfigRef:
    name: default
  projectID: ${GCP_PROJECT_ID}
  location: us-central1
  clusterVersion: 1.28
  releaseChannel: STABLE  # More stable release channel for production
  maintenanceWindow:
    startTime: "01:00"
  network:
    name: infracluster-vpc  # Using the same VPC as infracluster
    subnetName: infracluster-private-subnet
    clusterPodRangeName: infracluster-private-subnet-pods
    clusterSvcRangeName: infracluster-private-subnet-services
  nodeConfig:
    nodeCount: 3
    machineType: e2-standard-4
    diskSizeGb: 100
    diskType: pd-ssd  # Better performance for production
    serviceAccount: shared-gke-node-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com
    autoscaling:
      minNodeCount: 3
      maxNodeCount: 7
    labels:
      environment: prod
      role: application