apiVersion: platform.commercelab.io/v1alpha1
kind: GKECluster
metadata:
  name: staging-gke-cluster
  labels:
    environment: staging
    name: stagingcluster
    role: application
spec:
  providerConfigRef:
    name: default
  projectID: ${GCP_PROJECT_ID}
  location: us-central1
  clusterVersion: 1.28
  releaseChannel: REGULAR
  maintenanceWindow:
    startTime: "02:00"
  network:
    name: infracluster-vpc  # Using the same VPC as infracluster
    subnetName: infracluster-private-subnet
    clusterPodRangeName: infracluster-private-subnet-pods
    clusterSvcRangeName: infracluster-private-subnet-services
  nodeConfig:
    nodeCount: 2
    machineType: e2-standard-2
    diskSizeGb: 70
    diskType: pd-standard
    serviceAccount: shared-gke-node-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com
    autoscaling:
      minNodeCount: 2
      maxNodeCount: 5
    labels:
      environment: staging
      role: application