apiVersion: platform.commercelab.io/v1alpha1
kind: GKECluster
metadata:
  name: staging-gke-cluster
  labels:
    environment: staging
    name: stagingcluster
    role: application
spec:
  providerConfigRef:
    name: default
  clusterName: staging-gke-cluster
  projectID: ${GCP_PROJECT_ID}
  location: us-central1
  clusterVersion: 1.28
  releaseChannel: REGULAR
  maintenanceWindow:
    startTime: "02:00"
    recurrence: "FREQ=WEEKLY;BYDAY=SA,SU"
  
  # Network configuration - Dedicated VPC architecture
  networkConfig:
    useExistingNetwork: false
    # No host project needed for dedicated VPC architecture
  
  # Node configuration
  nodeConfig:
    nodeCount: 2
    machineType: e2-standard-2
    diskSizeGb: 70
    diskType: pd-standard
    serviceAccount: gke-node-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com
    autoscaling:
      minNodeCount: 2
      maxNodeCount: 5
    labels:
      environment: staging
      role: application
    
  # Security configuration  
  securityConfig:
    enableShieldedNodes: true
    enableIntegrityMonitoring: true
    enableSecureBoot: true
    enableNetworkPolicy: true
    privateClusterConfig:
      enablePrivateNodes: true
      enablePrivateEndpoint: false
      masterIpv4CidrBlock: "172.16.2.16/28" # Specific to staging environment
      masterAuthorizedNetworks:
        - cidrBlock: "0.0.0.0/0" # Allow access from the infrastructure cluster